### ISSUE TITLE
Not in center of card

### ISSUE THREAD

**Issue by poudenes** [fineemb/lovelace-thermostat-card#1]
As you can see. the thermostat is not in center of the card. 

![Screen Shot 2020-02-09 at 13 25 46](https://user-images.githubusercontent.com/4399532/74102024-f1349780-4b3f-11ea-8054-a92bcc95357d.png)

**Comment by fineemb** [comment]
Try to maintain the aspect ratio 1:1 
and 
````yaml
small_i: true
`````

**Comment by poudenes** [comment]
with small_i: true its ok. But then the thermostate is bigger. its ok ;)
