### ISSUE TITLE
No tick highlights

### ISSUE THREAD

**Issue by fpd2** [fineemb/lovelace-thermostat-card#12]
Is it possible to add a different (highlighted) color to the tick marks between the current temperature and the target temperature?
The original control on Codepen does have a different tick mark color (see image below:)
![th_codepen](https://user-images.githubusercontent.com/54507873/74731491-5ecf7a80-5248-11ea-90c1-308418920a02.png)
And this is the behavior in lovelace:
![th_hass](https://user-images.githubusercontent.com/54507873/74731567-845c8400-5248-11ea-9ed1-5c26f8a6ea20.png)
Also, when the heater is off, no tick mark highlights are visible:
![th_hass_off](https://user-images.githubusercontent.com/54507873/74732163-ea95d680-5249-11ea-8147-aa3f730fb7a7.png)

(btw: using Thermostat Lovelace card v1.2.8 on HASS 105.4, browsers: Safari and Chrome)

**Comment by fineemb** [comment]
Reconsidering processing of background color display
The next version may solve the problem
