### ISSUE TITLE
The tun on buttons are broken on HA 0.110.0

### ISSUE THREAD

**Issue by dmatik** [fineemb/lovelace-thermostat-card#15]
HI,
The buttons are broken on HA 0.110.0

**Comment by acrespog** [comment]
I get "Cannot read property 'setConfig' of undefined" error on 0.110.0 with v1.2.9 and v1.2.8. Correctly running until this version.

I tried to reinstall, change config to default,... with no success.

**Comment by fineemb** [comment]
fix 0.110.

**Comment by dmatik** [comment]
Thank you very much for so quick resolution!
