### ISSUE TITLE
The title above the chevron

### ISSUE THREAD

**Issue by dmatik** [fineemb/lovelace-thermostat-card#16]
Hi,
It seems that there is an issue with clicking on the target temperature up chevron, due it is behind the title. 
In the smaller size mode. 

Thanks in advance.

![image](https://user-images.githubusercontent.com/5577386/82975423-0ea14a80-9fe5-11ea-97aa-b542519fe137.jpeg)

**Comment by fineemb** [comment]
fix v1.3.0
