### ISSUE TITLE
Custom element doesn't exist: thermostat-card.

### ISSUE THREAD

**Issue by adizag** [fineemb/lovelace-thermostat-card#17]
Hi

installed the very last version of HACS (1.0.1), thermostat-card(v1.2.9) and HA (0.110.1).
I'm getting "Custom element doesn't exist: thermostat-card."

**Comment by ManCaveMedia** [comment]
I just installed this and got the same error.
Same after a restart of Home Assistant.

Code editor in Lovelace says: Cannot read property 'setConfig' of undefined
I'm using this card code:
```
- type: custom:thermostat-card
  entity: climate.living_room_thermostat
  title: Thermostaat
```
The Lovelace frontend shows a red rectangle with above code and the warning: No card type configured.

**Comment by plissje** [comment]
3rd on this one, same error.

**Comment by fineemb** [comment]
Is it a HACS configuration problem?

The /community_plugin endpoint that was used for lovelace elements has been removed, it was replaced by /hacsfiles.

**Comment by konnectedvn** [comment]
HACS issue. You have to add it to lovelace resource manually.
Go to Configurations > Lovelace Dashboards > Resources > Add > /hacsfiles/lovelace-thermostat-card/main.js

**Comment by the0ckid82** [comment]
i have tried this but it is still giving the same error `Cannot read property 'setConfig' of undefined
` also my main.js file is located at /www/community/lovelace-thermostat-card/main.js , i do not have a hacsfile dir in /config

**Comment by konnectedvn** [comment]
It's in the right place. /hacsfiles means /www/community.

**Comment by Scope666** [comment]
Same problem as everyone else, path is correct under Resources.

![image](https://user-images.githubusercontent.com/31927547/89961590-2796c080-dc10-11ea-9bff-32fcade49f4e.png)

![image](https://user-images.githubusercontent.com/31927547/89961611-3aa99080-dc10-11ea-8eef-2b6a5e3c1b70.png)

**Comment by Xites** [comment]
> Same problem as everyone else, path is correct under Resources.
> 
> ![image](https://user-images.githubusercontent.com/31927547/89961590-2796c080-dc10-11ea-9bff-32fcade49f4e.png)
> 
> ![image](https://user-images.githubusercontent.com/31927547/89961611-3aa99080-dc10-11ea-8eef-2b6a5e3c1b70.png)

Try without indent. That worked for me.
Just like this:

```
type: custom:thermostat-card
entity: climate.downstairs
small_i: true
title: test
```
