### ISSUE TITLE
Menu (3 dots) not visible

### ISSUE THREAD

**Issue by dmatik** [fineemb/lovelace-thermostat-card#18]
Hi,
Seems that the menu button (3 dots) is not visible anymore. Although it is still possible to tap on that area to get the whole settings pop-up opened.

Totally fine if this was the intention, maybe make it configurable. What do you think?

Thanks in advance. 

![image](https://user-images.githubusercontent.com/5577386/82975323-c3873780-9fe4-11ea-9895-92606c391610.jpeg)

**Comment by fineemb** [comment]
fix 1.3.0

**Comment by dmatik** [comment]
Hi,
Thanks a lot for fixing. 
Can you please advise why there is no new version in HACS yet?
