### ISSUE TITLE
The color on the scale is missing

### ISSUE THREAD

**Issue by dmatik** [fineemb/lovelace-thermostat-card#19]
Hi,
Since last HA update, 0.110.2, there is no scale coloring, blue, orange, depends on the AC operation mode. 
It is all white now.

![image](https://user-images.githubusercontent.com/5577386/83006036-4aa2d280-a01a-11ea-85a2-b65401706719.jpeg)

Thanks in advance.

**Comment by fineemb** [comment]
fix v1.3.0
