### ISSUE TITLE
Control icon can't be seen in default theme

### ISSUE THREAD

**Issue by konnectedvn** [fineemb/lovelace-thermostat-card#20]
Dark icons can't be seen when use default theme.
Screenshot: https://konnected.vn/wp-content/uploads/2020/06/konnected_vn_Lovelace-Thermostat-Card-Color-Issue-6-6-2020.png

**Comment by fineemb** [comment]
Is it the latest version?
v1.3.0 should have been fixed

**Comment by konnectedvn** [comment]
It's 1.2.9. Not seen 1.3.0 on HACS yet but I guess it will.

**Comment by konnectedvn** [comment]
> Is it the latest version?
> v1.3.0 should have been fixed

Released?

**Comment by Jaguaza** [comment]
@fineemb It happens to me too.

![Anotación 2020-06-27 132537](https://user-images.githubusercontent.com/46264854/85921353-09e9e380-b87c-11ea-94b2-cab04a4224df.png)

**Comment by Jaguaza** [comment]
@fineemb Installed today by HASC and installs 1.2.9.

Download dist and replace 1.2.9 files with 1.3.0 and it doesn't work. I have the same problem.

Do you need my theme data?

**Comment by fineemb** [comment]
release is forgotten-_-!!
