### ISSUE TITLE
Dial not turning orange when heating

### ISSUE THREAD

**Issue by danielbrunt57** [fineemb/lovelace-thermostat-card#27]
I am using the new Nest Integration.  The thermostat attributes are:
```
hvac_modes:
  - 'off'
  - heat
min_temp: 7
max_temp: 35
preset_modes:
  - none
  - eco
current_temperature: 21.6
temperature: 22
hvac_action: heating
preset_mode: none
friendly_name: Living Room
supported_features: 17
```
As you can see, hvac_action is reported as `heating` not `heat`.  I think the code triggers an orange dial when `hvac_action` is `heat`.  There is another thermostat-card project that allows you to map `off`, `heat` and `cool` to your thermostat's action states.

**Comment by alexelite** [comment]
I do not think this card is supposed to work the same way as the other card. This one turns the dial lines between the current temperature and the setpoint  orange for heating, and blue for cooling.

**Comment by danielbrunt57** [comment]
I'm using dark-thermostat now.
