### ISSUE TITLE
HACS installation is not working

### ISSUE THREAD

**Issue by peetereczek** [fineemb/lovelace-thermostat-card#7]
Please fix HACS installation

![image](https://user-images.githubusercontent.com/42431204/74418760-2f380100-4e49-11ea-9337-ca06835b9a1a.png)

Files are copied by HACS, but your card is not working

**Comment by peetereczek** [comment]
![image](https://user-images.githubusercontent.com/42431204/74418411-9d2ff880-4e48-11ea-8467-e117bd2dac29.png)

Take a look on the path script is looking for rest of libraries, it's completely wrong

**Comment by fineemb** [comment]
Please confirm the version of HACS
According to HACS logs, this issue has been fixed at 0.21.5
And I've tested the relevant version.

**Comment by peetereczek** [comment]
Please take a look on paths to files you are using

**Comment by peetereczek** [comment]
It should be community_plugin/lovelace-thermostat-card/styles.js instead of community_plugin/lovelace-thermostat-card/dist/styles.js?v=0.1

**Comment by fineemb** [comment]
Trying to clear the browser cache

**Comment by peetereczek** [comment]
Now it seems that it loaded
